- name: 'Sandstorm Two Factor Authentication'
  uriPattern: 'neos/two-factor-login'
  defaults:
    '@package': 'Sandstorm.NeosTwoFactorAuthentication'
    '@controller': 'Login'
    '@action': 'askForSecondFactor'
    '@format': 'html'
  httpMethods: ['GET']
  appendExceedingArguments: true

- name: 'Sandstorm Two Factor Authentication - Creation'
  uriPattern: 'neos/enable-two-factor-login/{@action}'
  defaults:
    '@package': 'Sandstorm.NeosTwoFactorAuthentication'
    '@controller': 'SecondFactorCreation'
    '@action': 'index'
    '@format': 'html'
  httpMethods: ['GET', 'POST']
  appendExceedingArguments: true


- name: 'Sandstorm Two Factor Authentication - Validation'
  uriPattern: 'neos/two-factor-login'
  defaults:
    '@package': 'Sandstorm.NeosTwoFactorAuthentication'
    '@controller': 'Authentication'
    '@action': 'checkOtp'
    '@format': 'html'
  httpMethods: ['POST']
  appendExceedingArguments: true

